### ISSUE TITLE
Features I'd like to see added

### ISSUE THREAD

**Issue by elementybt** [via5/Cue#3]
These are things I've thought of that I'd like to see.

**Able to save default settings**
When loading the plugin it'd be nice to be able to save default settings like sound, personality traits, etc. Embody has this where you set it up as you'd like it then save the settings which get auto loaded whenever the plugin is applied.

**Option to use Clockwise BJ sound effects**
You can turn up the SFX volume for the BJ plugin but it gets reset anytime the BJ is stopped and restarted.

**Option for wet genitals**
Auto-apply a wet genital texture after bj/insertion or after a certain excitement level.

**Cum effects**
Similar to the wet genitals but with cum instead.

**Auto hand roaming**
Don't know if this would even really be feasible in VAM, but have hands automatically move across themselves/their partner.

**Toe curl during orgasm**
👍

**Comment by via5** [comment]
I have a todo list that I'm keeping private for now and I've added some of your suggestions to it.

> Able to save default settings

I've added this to the list. In the meantime, you can always save and load options by using the two buttons at the bottom of the options.

> Option to use Clockwise BJ sound effects

Cue sets the sfx and moan volume to 0 when it starts the animation because it's handled by VamMoan instead. Doesn't this work for you?

> Option for wet genitals, Cum effects

I'd love to, but this would require automating something like DecalMaker, which would be real messy. So that'd be a no for now.

> Auto hand roaming

That's a common request. Procedural animations like this are generally very difficult. It's on my list, but don't hold your breath.

> Toe curl during orgasm

Added it to the list, I need to revisit that animation anyway.

**Comment by elementybt** [comment]
> > Option to use Clockwise BJ sound effects
> 
> Cue sets the sfx and moan volume to 0 when it starts the animation because it's handled by VamMoan instead. Doesn't this work for you?

The default plugin preset comes with VAMMoan BJ sound effects turned off. Even with "Play BJ sounds" enabled in Cue it doesn't work unless you manually enable it in VAMMoan.

However, I use my own custom plugin preset with it already enabled. My problem is that VAMMoan is kind of fickle in that it'll just stop playing the sound effects a lot, especially if there's not a lot of movement going on. I also just like the Clockwise sound effect (SFX specifically, not the moan) better, but that's just an imo.

**Comment by via5** [comment]
> The default plugin preset comes with VAMMoan BJ sound effects turned off.

Oh okay, I see what's going on. Some version after 11 changed the way the BJ sounds work. It used to be a discrete state, but now it looks like a checkbox that's independent of moaning. Cue is not compatible with the newer version, then. I wasn't even aware of that change. I'll work on it.

I'll also change Cue to only mute CW's sound effects on load (or the first time the BJ animation is played if the CW plugin wasn't present on load). Would that work?

**Comment by elementybt** [comment]
Sure, that would be great. Thanks for looking over my ideas.

**Comment by via5** [comment]
I've fixed the missing BJ audio in cbbe9ab660674106765db11dff75185d45a7aaab (will release with 2.2) and added some of the other suggestions to my list, so I'm closing this.

**Comment by via5** [comment]
Just to let you know the status of your suggestions now that Cue 3.1 is out:

> Able to save default settings

That's implemented, there's a new button to save the default settings.

> Auto hand roaming

I added simple hand and finger movements when linked to breasts, chest, back or belly.

> Toe curl during orgasm

I won't be implementing this because it also moves most shoes. I'd need to determine whether shoes are being worn or not, which is not something I can do right now.
